name: playit_mobile
description: PlayIt Mobile — Multi-stem audio player
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.18
  flutter_soloud: ^3.1.10
  file_picker: ^8.1.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/main_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/main_icon.png"
  min_sdk_android: 21
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: SairaStencilOne
      fonts:
        - asset: assets/fonts/SairaStencilOne-Regular.ttf
